name: Update LeetCode Stats

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch LeetCode stats
        id: leetcode
        run: |
          # Fetch contest ranking info
          contest_response=$(curl -s "https://alfa-leetcode-api.onrender.com/userContestRankingInfo/furic")

          # Extract contest values using jq
          rating=$(echo "$contest_response" | jq -r '.rating' | cut -d'.' -f1)
          global_ranking=$(echo "$contest_response" | jq -r '.globalRanking')
          total_participants=$(echo "$contest_response" | jq -r '.totalParticipants')

          # Fetch user profile for solved problems
          profile_response=$(curl -s "https://alfa-leetcode-api.onrender.com/userProfile/furic")

          # Extract solve statistics
          total_solved=$(echo "$profile_response" | jq -r '.totalSolved')
          total_questions=$(echo "$profile_response" | jq -r '.totalQuestions')
          solve_percentage=$(echo "scale=1; $total_solved * 100 / $total_questions" | bc)

          # Format numbers with commas
          formatted_ranking=$(echo "$global_ranking" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
          formatted_total=$(echo "$total_participants" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
          formatted_solved=$(echo "$total_solved" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
          formatted_questions=$(echo "$total_questions" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')

          echo "rating=$rating" >> $GITHUB_OUTPUT
          echo "ranking=$formatted_ranking" >> $GITHUB_OUTPUT
          echo "total=$formatted_total" >> $GITHUB_OUTPUT
          echo "solved=$formatted_solved" >> $GITHUB_OUTPUT
          echo "questions=$formatted_questions" >> $GITHUB_OUTPUT
          echo "percentage=$solve_percentage" >> $GITHUB_OUTPUT

      - name: Update README badges
        run: |
          # Update Contest Rating badge
          sed -i "s/Contest_Rating-[0-9]*/Contest_Rating-${{ steps.leetcode.outputs.rating }}/g" README.md

          # Update Global Ranking badge
          sed -i "s/Global_Ranking-[0-9,]*\/[0-9,]*/Global_Ranking-${{ steps.leetcode.outputs.ranking }}\/${{ steps.leetcode.outputs.total }}/g" README.md

          # Update Problems Solved badge
          sed -i "s/Solved-[0-9,]*\/[0-9,]*/Solved-${{ steps.leetcode.outputs.solved }}\/${{ steps.leetcode.outputs.questions }}/g" README.md

          # Update Solve Percentage badge
          sed -i "s/Solve_Rate-[0-9.]*%25/Solve_Rate-${{ steps.leetcode.outputs.percentage }}%25/g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "🤖 Update LeetCode stats: Rating ${{ steps.leetcode.outputs.rating }}, Ranking ${{ steps.leetcode.outputs.ranking }}/${{ steps.leetcode.outputs.total }}, Solved ${{ steps.leetcode.outputs.solved }}/${{ steps.leetcode.outputs.questions }} (${{ steps.leetcode.outputs.percentage }}%)

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
          fi